### ISSUE TITLE
Dependency Needed

### ISSUE THREAD

**Issue by apmunch** [sshell/reddit-analyzer#4]
Any idea what dependency will resolve the following error?

`Traceback (most recent call last):
  File "reddit-analyzer.py", line 190, in <module>
    timeGraph(timelist)
  File "reddit-analyzer.py", line 142, in timeGraph
    d.append(tuple([g, tgdata[e][1]]))
IndexError: list index out of range`

**Comment by coryshaw1** [comment]
This is due to #1. Hopefully fixed with #3, if you could please test

**Comment by apmunch** [comment]
Does not seem to be working for me.

`$ git pull
Already up to date.
~/tools/reddit-analyzer$ python3 reddit-analyzer.py USERNAME
 --- fetching data for user: USERNAME ---
 
[+] username        : USERNAME
[+] creation date   : 2016-06-19 20:01:19
[+] last action     : 2019-12-18 11:53:21
[+] verified email  : True
---
[+] total comments  : 237
[+] comment karma   : 461
---
[+] total links     : 15
[+] link karma      : 112
---
[+] location based reddit(s): set()
 
Comment Activity
###############################################################################
████████████████                                        37    asknetsec        
███████████                                             25    security         
██████████                                              23    sysadmin         
█████                                                   13    eero             
███                                                      8    crossfit         
███                                                      7    netsec           
█                                                        3    cybersecurity    
█                                                        3    iama             
                                                         2    asktechnology    
                                                         2    k12sysadmin      
                                                         2    nest             
                                                         2    citrix           
                                                         2    malware          
                                                         2    documentaries    
                                                         1    hacking          
                                                         1    protonmail       
                                                         1    sccm             
                                                         1    csharp           
                                                         1    mildlyinteresting
                                                         1    music            
                                                         1    aww              
                                                         1    earthporn        
 
Traceback (most recent call last):
  File "reddit-analyzer.py", line 190, in <module>
    timeGraph(timelist)
  File "reddit-analyzer.py", line 142, in timeGraph
    d.append(tuple([g, tgdata[e][1]]))
IndexError: list index out of range`

**Comment by coryshaw1** [comment]
@apmunch  The line numbers from the stacktrace do not match the changes from #3. Make sure you are using the file from https://github.com/coryshaw1/reddit-analyzer

**Comment by apmunch** [comment]
Unclear why git pull didn't work, but a complete lift and replace fixed it. Thank you for the help.
